# Generated by Django 5.0.2 on 2024-02-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_category_contact_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Sem categoria', max_length=50),
        ),
    ]
